# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xcvu440-flga2892-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/test/test.cache/wt} [current_project]
set_property parent.project_path {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/test/test.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/test/test.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/ALU_SIMD_Width_parameterized_HighLevelDescribed_auto.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/ALU_T_C3x2_F2_27bits_18bits_HighLevelDescribed_auto_DSP48E2_new.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/C_Register_block.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/DSP_proposed.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/D_Register_block.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/Dual_A_Register_block_proposed.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/Dual_B_Register_block_proposed.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/XYZW_manager_proposed.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/carry_in_manager.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/inmode_manager.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/mult_chain_stream_mode_manager.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/multiplier_S_C3x2_F2_9bits_9bits_HighLevelDescribed_auto.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/multiplier_T_C3x2_F2_27bits_18bits_HighLevelDescribed_auto.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/multiplier_output_manager_proposed.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/operation_manager.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/output_manager_proposed.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/pattern_detection.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/wide_xor_block.v}
  {/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/DSP_proposed_RFless_freezer.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/test/test.srcs/constrs_1/new/Clock_cons.xdc}}
set_property used_in_implementation false [get_files {{/home/ramintp/MEGA/USYD/2018_R2/temp/Standard Cell/Verilog model/test/test.srcs/constrs_1/new/Clock_cons.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top DSP_proposed_RFless_freezer -part xcvu440-flga2892-1-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DSP_proposed_RFless_freezer.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DSP_proposed_RFless_freezer_utilization_synth.rpt -pb DSP_proposed_RFless_freezer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
