@startuml

title Start

start

:Selected projection
     subset = {};

while (Any new benchmark case?)  is (Yes)
  :Find the best performing 
  projections for that case;
  
  if (Any of the best performing projections are 
  already in the selected projection subset?) then (yes)
    
  else (no)
    :Add one of the projections (randomly) 
       to the selected projection subset;
  endif

endwhile (No)

:   Generate MLBlock Verilog model
using the selected projection subset;

stop

@enduml

